#!/usr/bin/env bash
# #ddev-generated
## Description: Show the VRT HTML diff report
## Usage: vrt-report
## Example: ddev vrt-report

cd /var/www/html/.ddev/drupal-vrt
echo -e "Report will be available at: \033[1;36mhttps://${DDEV_HOSTNAME}:9324\033[0m"
echo "Press Ctrl+C to quit."
npx playwright show-report ../../playwright-report --host 0.0.0.0 --port 9323 2>&1 | grep -v "Serving HTML report at"
